In [1]:

library(MultiAssayExperiment)
library(RaggedExperiment)
library(data.table)

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians



Attaching package: ‘data.table’


The following object is masked from ‘package:SummarizedExperiment’:

    shift


The following object is masked from ‘package:GenomicRanges’:

    shift


The following object is masked from ‘package:IRanges’:

    shift


The following objects are masked from ‘package:S4Vectors’:

    first, second

In [2]:
drop_sa <- fread("/omics/odcf/analysis/hipo/hipo_021/outlier_analysis/sample_data/master_drop_sample_annotation_sizeFactorFiltered_0.1.tsv")
drop_sa[, master_pid := gsub( "_", ".", nct_pid)]

In [3]:
load("/omics/odcf/analysis/OE0246_projects/datamaster/dataMASTER_release/object/dataMASTER_241104123708.RData")
load("/omics/odcf/analysis/OE0246_projects/datamaster/ext_data/annotations/gencode19_gns_lite.RData")

In [4]:
myobj = dataMASTER[,,c("cnv", "cnv_germline", "sv")] # class: MAE

Warning message:
“'experiments' dropped; see 'drops()'”

harmonizing input:
  removing 62967 sampleMap rows not in names(experiments)
  removing 105 colData rownames not in sampleMap 'primary'

In [5]:
# 1. Get all unique column names from the MEA
all_colnames <- unlist(colnames(myobj))

# 2. Initialize an empty character vector to store matches
matched_cols <- character()

# 3. Loop through each ID in your sa table
for (pid in drop_sa$master_pid) {
  # We use fixed = TRUE because your IDs have dots (.) 
  # which would otherwise be treated as wildcards in regex
  hits <- grep(pid, all_colnames, value = TRUE, fixed = TRUE)
  
  # Append new hits to our master list
  matched_cols <- c(matched_cols, hits)
}

# 4. Remove duplicates (in case one column matched multiple PIDs)
matched_cols <- unique(matched_cols)

In [13]:
germline_cnv_df <- as.data.frame(myobj[["cnv_germline"]])
library(data.table)
setDT(germline_cnv_df)

# Take a look at the first few rows
germline_cnv_df

       group group_name              seqnames start     end       width  strand
1      1     WES.192P9WW.tumor       3         11645548  11646305   758  *
2      1     WES.192P9WW.tumor       6        123698950 123699293   344  *
3      1     WES.192P9WW.tumor       16        70993300  70993973   674  *
4      1     WES.192P9WW.tumor       19        14877540  14878171   632  *
5      1     WES.192P9WW.tumor       19        15784117  15789465  5349  *
6      1     WES.192P9WW.tumor       22        17264052  17265549  1498  *
7      1     WES.192P9WW.tumor       X        153418163 153418831   669  *
8      1     WES.192P9WW.tumor       Y         14951540  14959121  7582  *
9      2     WES.8ZTUHJ.metastasis   1        151336530 151403567 67038  *
10     2     WES.8ZTUHJ.metastasis   2         90108254  90109330  1077  *
11     2     WES.8ZTUHJ.metastasis   3         11645548  11646305   758  *
12     2     WES.8ZTUHJ.metastasis   5         64096879  64097409   531  *
13     2     WES.8ZTUHJ.metastasis   11         5797145   5804835  7691  *
14     2     WES.8ZTUHJ.metastasis   12         8015715   8024625  8911  *
15     2     WES.8ZTUHJ.metastasis   12         8075167   8089033 13867  *
16     2     WES.8ZTUHJ.metastasis   16        70993300  70993973   674  *
17     2     WES.8ZTUHJ.metastasis   19        15784117  15789465  5349  *
18     2     WES.8ZTUHJ.metastasis   Y         14851209  14870822 19614  *
19     2     WES.8ZTUHJ.metastasis   Y         14951540  14959121  7582  *
20     2     WES.8ZTUHJ.metastasis   Y         21901164  21903497  2334  *
21     3     WES.1NS1.tumor          1         89476303  89478009  1707  *
22     3     WES.1NS1.tumor          2        179296706 179309541 12836  *
23     3     WES.1NS1.tumor          5         70307338  70309043  1706  *
24     3     WES.1NS1.tumor          6         35755365  35765381 10017  *
25     3     WES.1NS1.tumor          7         38388453  38389180   728  *
26     3     WES.1NS1.tumor          8         39311300  39335537 24238  *
27     3     WES.1NS1.tumor          10       124344469 124351722  7254  *
28     3     WES.1NS1.tumor          10       133770882 133773556  2675  *
29     3     WES.1NS1.tumor          11        18955479  18956734  1256  *
30     3     WES.1NS1.tumor          11       107652059 107663840 11782  *
⋮      ⋮     ⋮                       ⋮        ⋮         ⋮         ⋮      ⋮
100074 5611  WGS.99PLK9.metastasis02 12        80859135  80866280   7146 *
100075 5611  WGS.99PLK9.metastasis02 16        84328002  84693773 365772 *
100076 5611  WGS.99PLK9.metastasis02 19          361500    362676   1177 *
100077 5611  WGS.99PLK9.metastasis02 19        15784190  15789625   5436 *
100078 5611  WGS.99PLK9.metastasis02 20        20551852  20552840    989 *
100079 5611  WGS.99PLK9.metastasis02 22        24375883  24384930   9048 *
100080 5612  WGS.99S7ZW.metastasis   1        152572888 152586824  13937 *
100081 5612  WGS.99S7ZW.metastasis   5        147553547 147554183    637 *
100082 5612  WGS.99S7ZW.metastasis   8         17580500  17581921   1422 *
100083 5612  WGS.99S7ZW.metastasis   8        109667272 109800094 132823 *
100084 5612  WGS.99S7ZW.metastasis   9           212858    271979  59122 *
100085 5612  WGS.99S7ZW.metastasis   11        17307931  17308514    584 *
100086 5612  WGS.99S7ZW.metastasis   12        21556103  21572778  16676 *
100087 5612  WGS.99S7ZW.metastasis   15        27017327  27018471   1145 *
100088 5612  WGS.99S7ZW.metastasis   19        55476188  55476995    808 *
100089 5612  WGS.99S7ZW.metastasis   20         3126915   3130156   3242 *
100090 5613  WGS.99TT5V.tumor        2         31287741  31288523    783 *
100091 5613  WGS.99TT5V.tumor        5        147553547 147554183    637 *
100092 5613  WGS.99TT5V.tumor        10        83634820  83992825 358006 *
100093 5613  WGS.99TT5V.tumor        10       124343588 124353364   9777 *
100094 5613  WGS.99TT5V.tumor        10       135138677 135141769   3093 *
100095 5613  WGS.99TT5V.tumor        15        76344158  76345960   1803 *
100096 5613  WGS.99TT5V.tumor        17           69164     69777    614 *
100097 5613  WGS.99TT5V.tumor        19        15788821  15789625    805 *
100098 5614  WGS.9A77B1.metastasis   7        111957987 111958578    592 *
100099 5614  WGS.9A77B1.metastasis   10        46965465  47088570 123106 *
100100 5614  WGS.9A77B1.metastasis   10       124343588 124353364   9777 *
100101 5614  WGS.9A77B1.metastasis   19        15784190  15789625   5436 *
100102 5614  WGS.9A77B1.metastasis   19        18347418  18348121    704 *
100103 5614  WGS.9A77B1.metastasis   22        46067428  46068063    636 *
       Type CN NP QUAL Confidence
1      DEL  1   1   65 LOW
2      DEL  1   1   42 HIGH
3      DEL  0   1   44 HIGH
4      DEL  1   1   34 LOW
5      DEL  0   2  645 HIGH
6      DEL  0   1  163 HIGH
7      DEL  0   1  205 HIGH
8      DUP  3   6   51 LOW
9      DUP  3  35  145 HIGH
10     DEL  1   2   53 LOW
11     DEL  0   1  441 HIGH
12     DEL  1   1   39 LOW
13     DEL  0   3 1599 HIGH
14     DEL  1   5  112 HIGH
15     DEL  1   8  113 HIGH
16     DEL  0   1   82 HIGH
17     DEL  0   2  548 HIGH
18     DUP  2   3   31 LOW
19     DUP  2   6   56 LOW
20     DUP  2   2   39 LOW
21     DEL  1   3  249 LOW
22     DUP  3   5  115 LOW
23     DEL  1   2  329 HIGH
24     DUP  3   7   44 HIGH
25     DEL  0   2  208 LOW
26     DUP  4  11   42 LOW
27     DEL  1  10  864 LOW
28     DUP  3   8  148 LOW
29     DUP  3   5   82 LOW
30     DUP  3   6   60 HIGH
⋮      ⋮    ⋮  ⋮  ⋮    ⋮
100074 DEL  1   3  403 HIGH
100075 DUP  3  57 2690 HIGH
100076 DEL  1   1   66 HIGH
100077 DEL  0   2  497 LOW
100078 DEL  1   2  184 HIGH
100079 DUP  4   7  125 LOW
100080 DUP  4   2   55 LOW
100081 DEL  0   1  182 LOW
100082 DEL  1   2  133 HIGH
100083 DEL  1   3  492 HIGH
100084 DUP  3   3  187 HIGH
100085 DEL  1   1   74 HIGH
100086 DUP  3   3  137 HIGH
100087 DEL  1   3   33 HIGH
100088 DEL  0   2  126 LOW
100089 DUP  3   1   75 HIGH
100090 DEL  1   1  113 HIGH
100091 DEL  0   1  184 LOW
100092 DUP  3   5  268 HIGH
100093 DEL  1   8 1032 LOW
100094 DUP  3   4  226 HIGH
100095 DEL  1   3  402 HIGH
100096 DEL  0   1  106 LOW
100097 DEL  0   1  369 LOW
100098 DEL  1   1   76 HIGH
100099 DUP  3  10  139 LOW
100100 DEL  1   8  877 LOW
100101 DEL  0   2  293 LOW
100102 DEL  1   1  115 HIGH
100103 DEL  1   1   89 HIGH

In [6]:
cnv_germline  = getWithColData(myobj, "cnv_germline")
actual_cnv_cols <- colnames(cnv_germline)

# 2. Filter your matched_cols to only include those present in CNV
valid_cnv_matches <- intersect(matched_cols, actual_cnv_cols)

# 3. Now subset safely
cnv_germline <- cnv_germline[, valid_cnv_matches, ]
cnv_germline


cnv_germline@assays[[1]]$Gene = as.character(NA)
sv = as(cnv_germline, "GRangesList")
 
n = length(sv)
sv = lapply(1:100, function(i) {
  svPID = sv[[i]]
  # cat(sprintf("\r%s/%s", i, n))
  idx = findOverlaps(svPID, gencode19_gns_lite)
  gns = tapply(idx@to, idx@from, function(i) {
    paste(gencode19_gns_lite$gene_name[i], collapse=",")
  })
  svPID$Gene[as.numeric(names(gns))] = unname(gns)
  svPID
})
sv_re = RaggedExperiment(sv, colData=colData(cnv_germline))

myobj[["cnv_germline"]] = sv_re


germline_cnv_dt <- as.data.table(myobj[["cnv_germline"]]@assays[[1]])
#fwrite(germline_cnv_dt, "/omics/odcf/analysis/hipo/hipo_021/outlier_analysis/vcf/cnv/germline_cnv.tsv", sep="\t")

class: RaggedExperiment
dim: 100103 3817
assays(5): Type CN NP QUAL Confidence
rownames: NULL
colnames(3817): WES.00JN.metastasis WES.019E.metastasis ...
  WGS.ZZU2PY.tumor WGS.ZZXYWB.metastasis05
colData names(59): SampleID ProjectID ... INDEL_ClinFunOnTarget
  MutPerMb

ERROR: Error in RaggedExperiment(sv, colData = colData(cnv_germline)): length() of 'rowRanges' is not equal to nrow() of 'colData'

   seqnames start     end       width strand Type CN NP QUAL Confidence
1  6         32606437  32611248  4812 *      DEL  1   6 112  LOW
2  7        100550616 100551693  1078 *      DUP  3   4  31  HIGH
3  7        122254929 122262012  7084 *      DEL  1   2 118  HIGH
4  10       124344469 124351722  7254 *      DEL  1  10 531  HIGH
5  11        18955479  18956604  1126 *      DUP  3   4  30  LOW
6  12       131953679 131954299   621 *      DEL  0   1  58  LOW
7  12       133779224 133811272 32049 *      DUP  3  15 126  HIGH
8  14       106372747 106376611  3865 *      DEL  1   4 147  LOW
9  17        19532621  19536854  4234 *      DEL  1   4 139  HIGH
10 19        15784309  15789375  5067 *      DEL  0   2 349  LOW
11 19        50452906  50455915  3010 *      DEL  1   4 143  HIGH
12 19        51509392  51510204   813 *      DEL  1   2  86  HIGH
   Gene
1  HLA-DQA1
2  MUC3A
3  CADPS2
4  DMBT1
5  MRGPRX1,RP11-583F24.8
6  RP11-897M7.1
7  ZNF268,AC226150.4,AC226150.3,ANHX
8  IGHD2-8,IGHD1-7,IGHD6-6
9  CTD-2104P17.1
10 CYP4F12
11 CTC-326K19.6,SIGLEC11
12 CTB-147C22.9,KLK9,KLK9

In [ ]:
cnv  = getWithColData(myobj, "cnv")
actual_cnv_cols <- colnames(cnv)

# 2. Filter your matched_cols to only include those present in CNV
valid_cnv_matches <- intersect(matched_cols, actual_cnv_cols)

# 3. Now subset safely
cnv <- cnv[, valid_cnv_matches, ]
cnv


cnv@assays[[1]]$Gene = as.character(NA)
sv = as(cnv, "GRangesList")
 
n = length(sv)
sv = lapply(1:n, function(i) {
  svPID = sv[[i]]
  # cat(sprintf("\r%s/%s", i, n))
  idx = findOverlaps(svPID, gencode19_gns_lite)
  gns = tapply(idx@to, idx@from, function(i) {
    paste(gencode19_gns_lite$gene_name[i], collapse=",")
  })
  svPID$Gene[as.numeric(names(gns))] = unname(gns)
  svPID
})
sv_re = RaggedExperiment(sv, colData=colData(cnv_germline))

myobj[["cnv"]] = sv_re

# show the example
head(myobj[["cnv"]]@assays[[1]])

In [ ]:
head(myobj[["cnv"]]@assays[[1]])

In [5]:
cnv_germline  = getWithColData(myobj, "cnv_germline")
assayNames(cnv_germline)
cnv_germline = cnv_germline[, "WGS.MNL8UP.tumor"]
cnv_germline

[1] "Type"       "CN"         "NP"         "QUAL"       "Confidence"

class: RaggedExperiment
dim: 100103 1
assays(5): Type CN NP QUAL Confidence
rownames: NULL
colnames(1): WGS.MNL8UP.tumor
colData names(59): SampleID ProjectID ... INDEL_ClinFunOnTarget
  MutPerMb

In [ ]:
cnv_germline@assays[[1]]$Gene = as.character(NA)
sv = as(cnv_germline, "GRangesList")
sv

GRangesList object of length 1:
$WGS.MNL8UP.tumor
GRanges object with 4 ranges and 6 metadata columns:
      seqnames            ranges strand |     Type        CN        NP
         <Rle>         <IRanges>  <Rle> | <factor> <integer> <integer>
  [1]        2 27872732-28211204      * |      DUP         3        45
  [2]        3 75758544-75788746      * |      DEL         0         3
  [3]       19 15784190-15789625      * |      DEL         0         2
  [4]       22 24375883-24384930      * |      DUP         4         7
           QUAL Confidence        Gene
      <integer>   <factor> <character>
  [1]      1123       HIGH        <NA>
  [2]       425       LOW         <NA>
  [3]       224       LOW         <NA>
  [4]        73       LOW         <NA>
  -------
  seqinfo: 24 sequences from hg19_1KGRef_PhiX genome

In [6]:
cnv_germline@assays[[1]]$Gene = as.character(NA)
sv = as(cnv_germline, "GRangesList")
 
n = length(sv)
sv = lapply(1:n, function(i) {
  svPID = sv[[i]]
  # cat(sprintf("\r%s/%s", i, n))
  idx = findOverlaps(svPID, gencode19_gns_lite)
  gns = tapply(idx@to, idx@from, function(i) {
    paste(gencode19_gns_lite$gene_name[i], collapse=",")
  })
  svPID$Gene[as.numeric(names(gns))] = unname(gns)
  svPID
})
sv_re = RaggedExperiment(sv, colData=colData(cnv_germline))

myobj[["cnv_germline"]] = sv_re

# show the example
head(myobj[["cnv_germline"]]@assays[[1]])

harmonizing input:
  removing 5613 sampleMap rows with 'colname' not in colnames of experiments

GRanges object with 4 ranges and 6 metadata columns:
      seqnames            ranges strand |     Type        CN        NP
         <Rle>         <IRanges>  <Rle> | <factor> <integer> <integer>
  [1]        2 27872732-28211204      * |      DUP         3        45
  [2]        3 75758544-75788746      * |      DEL         0         3
  [3]       19 15784190-15789625      * |      DEL         0         2
  [4]       22 24375883-24384930      * |      DUP         4         7
           QUAL Confidence                   Gene
      <integer>   <factor>            <character>
  [1]      1123       HIGH GPN1,SUPT7L,SLC4A1AP..
  [2]       425       LOW  ZNF717,RN7SL92P,MIR4..
  [3]       224       LOW                 CYP4F12
  [4]        73       LOW        KB-226F1.1,GSTT1
  -------
  seqinfo: 24 sequences from hg19_1KGRef_PhiX genome

In [8]:
cnv_germline_dt <- as.data.table(myobj[["cnv_germline"]]@assays[[1]])
cnv_germline_dt

  seqnames start    end      width  strand Type CN NP QUAL Confidence
1 2        27872732 28211204 338473 *      DUP  3  45 1123 HIGH
2 3        75758544 75788746  30203 *      DEL  0   3  425 LOW
3 19       15784190 15789625   5436 *      DEL  0   2  224 LOW
4 22       24375883 24384930   9048 *      DUP  4   7   73 LOW
  Gene
1 GPN1,SUPT7L,SLC4A1AP,AC074091.13,MRPL33,AC110084.1,RBKS,BRE,RP11-674I16.1
2 ZNF717,RN7SL92P,MIR4273
3 CYP4F12
4 KB-226F1.1,GSTT1

In [17]:
cnv@assays[[1]]$Gene = as.character(NA)
sv = as(cnv, "GRangesList")
 
n = length(sv)
sv = lapply(1:n, function(i) {
  svPID = sv[[i]]
  # cat(sprintf("\r%s/%s", i, n))
  idx = findOverlaps(svPID, gencode19_gns_lite)
  gns = tapply(idx@to, idx@from, function(i) {
    paste(gencode19_gns_lite$gene_name[i], collapse=",")
  })
  svPID$Gene[as.numeric(names(gns))] = unname(gns)
  svPID
})
sv_re = RaggedExperiment(sv, colData=colData(cnv_germline))

myobj[["cnv"]] = sv_re

# show the example
head(myobj[["cnv"]]@assays[[1]])
cnv_dt <- as.data.table(myobj[["cnv"]]@assays[[1]])
cnv_dt

GRanges object with 6 ranges and 8 metadata columns:
      seqnames            ranges strand |       TCN  CovRatio       BAF
         <Rle>         <IRanges>  <Rle> | <numeric> <numeric> <numeric>
  [1]        1   840009-12839977      * |   2.00164   1.04347        NA
  [2]        1 13780016-19490045      * |   2.00164   1.04347        NA
  [3]        1 19490046-19499979      * |   1.82232   0.95840        NA
  [4]        1 19499980-25510000      * |   2.00164   1.04347        NA
  [5]        1 25510001-25520840      * |   1.80672   0.95100        NA
  [6]        1 25520841-51969987      * |   2.00164   1.04347        NA
         c1Mean    c2Mean     Type       LOH                   Gene
      <numeric> <numeric> <factor> <logical>            <character>
  [1]   1.00082   1.00082      CNN     FALSE RP11-54O7.16,RP11-54..
  [2]   1.00082   1.00082      CNN     FALSE LRRC38,RP4-597A16.2,..
  [3]        NA        NA      CNN     FALSE                   UBR4
  [4]   1.00082   1.00082      CNN     FALSE UBR4,RP1-43E13.2,EMC..
  [5]        NA        NA      CNN     FALSE                   <NA>
  [6]   1.00082   1.00082      CNN     FALSE RP4-706G24.1,SYF2,C1..
  -------
  seqinfo: 24 sequences from hg19_1KGRef_PhiX genome

    seqnames start     end       width    strand TCN         CovRatio
1   1           840009  12839977 11999969 *      2.001637    1.0434750
2   1         13780016  19490045  5710030 *      2.001637    1.0434750
3   1         19490046  19499979     9934 *      1.822315    0.9584000
4   1         19499980  25510000  6010021 *      2.001637    1.0434750
5   1         25510001  25520840    10840 *      1.806718    0.9510000
6   1         25520841  51969987 26449147 *      2.001637    1.0434750
7   1         51969987  51980013    10027 *      2.179377    1.1278000
8   1         51980014 120529963 68549950 *      2.001637    1.0434750
9   1        121220004 121229986     9983 *      2.001637    1.0434750
10  1        144010127 144019970     9844 *      2.039208    1.0613000
11  1        144920087 144948894    28808 *      2.001637    1.0434750
12  1        144948895 144952639     3745 *      2.073565    1.0776000
13  1        144952640 145739956   787317 *      2.001637    1.0434750
14  1        146540101 147829895  1289795 *      2.001637    1.0434750
15  1        149815060 220124938 70309879 *      2.001637    1.0434750
16  1        220124939 220133381     8443 *      1.348692    0.7337000
17  1        220133382 220223020    89639 *      1.067933    0.6005000
18  1        220223021 249209945 28986925 *      2.001637    1.0434750
19  2            20016     30021    10006 *      2.279287    1.1752000
20  2            30022  19119939 19089918 *      2.001637    1.0434750
21  2         19119939  19130003    10065 *      2.388050    1.2268000
22  2         19130004  33179511 14049508 *      2.001637    1.0434750
23  2         33179512  33460507   280996 *      1.002026    0.5692317
24  2         33460508  44385000 10924493 *      2.001637    1.0434750
25  2         44385001  44410022    25022 *      2.142912    1.1105000
26  2         44410023  59070019 14659997 *      2.001637    1.0434750
27  2         59070020  59089961    19942 *      2.166941    1.1219000
28  2         59089961  87059860 27969900 *      2.001637    1.0434750
29  2         88330099  89149998   819900 *      2.001637    1.0434750
30  2         89149998  89160000    10003 *      1.850960    0.9719899
⋮   ⋮        ⋮         ⋮         ⋮        ⋮      ⋮           ⋮
295 X          1761586  58499983 56738398 *      1.003690231 1.0462
296 X         61750000  79090023 17340024 *      0.995259022 1.0382
297 X         79090023  79099982     9960 *      1.158297522 1.1929
298 X         79099982  79270016   170035 *      0.954156879 0.9992
299 X         79270016  79290103    20088 *      1.039522868 1.0802
300 X         79290104  88459980  9169877 *      0.915794879 0.9628
301 X         88990017  89349936   359920 *      0.855722516 0.9058
302 X         90140199  91529952  1389754 *      0.866261527 0.9158
303 X         92380000 105550099 13170100 *      0.977553484 1.0214
304 X        105550100 105559976     9877 *      1.145334538 1.1806
305 X        105559976 106940004  1380029 *      0.995996753 1.0389
306 X        106940004 106949905     9902 *      1.210571016 1.2425
307 X        106949905 134010283 27060379 *      1.004533352 1.0470
308 X        134010284 134049988    39705 *      1.157665181 1.1923
309 X        134049988 142369949  8319962 *      0.968911495 1.0132
310 X        142369949 142380008    10060 *      1.124678077 1.1610
311 X        142380008 151329236  8949229 *      0.977237313 1.0211
312 X        151329237 151361865    32629 *      0.042216258 0.1339
313 X        151361866 154929639  3567774 *      1.003584841 1.0461
314 Y          2653090   2919837   266748 *      0.971335467 1.0155
315 Y          3712028   3719919     7892 *      0.991570368 1.0347
316 Y          6420014  10041053  3621040 *      0.904728918 0.9523
317 Y         10041054  10069977    28924 *      0.018819654 0.1117
318 Y         13130467  19558992  6428526 *      0.931498005 0.9777
319 Y         20802956  23659722  2856767 *      0.896086929 0.9441
320 Y         23706804  23808171   101368 *      0.891238984 0.9395
321 Y         23808172  24030632   222461 *      0.000000000 0.0000
322 Y         24319099  24381337    62239 *      0.000000000 0.0000
323 Y         24381338  24508205   126868 *      0.001535676 0.0953
324 Y         28780461  28789809     9349 *      0.887866500 0.9363
    BAF       c1Mean       c2Mean   Type LOH
1          NA 1.0008183503 1.000818 CNN  FALSE
2          NA 1.0008183503 1.000818 CNN  FALSE
3          NA           NA       NA CNN  FALSE
4          NA 1.0008183503 1.000818 CNN  FALSE
5          NA           NA       NA CNN  FALSE
6          NA 1.0008183503 1.000818 CNN  FALSE
7          NA           NA       NA CNN  FALSE
8          NA 1.0008183503 1.000818 CNN  FALSE
9          NA           NA       NA CNN  FALSE
10         NA           NA       NA CNN  FALSE
11         NA           NA       NA CNN  FALSE
12         NA           NA       NA CNN  FALSE
13         NA 1.0008183503 1.000818 CNN  FALSE
14         NA 1.0008183503 1.000818 CNN  FALSE
15         NA 1.0008183503 1.000818 CNN  FALSE
16         NA           NA       NA NA   FALSE
17         NA           NA       NA DEL  FALSE
18         NA 1.0008183503 1.000818 CNN  FALSE
19         NA           NA       NA CNN  FALSE
20         NA 1.0008183503 1.000818 CNN  FALSE
21         NA           NA       NA NA   FALSE
22         NA 1.0008183503 1.000818 CNN  FALSE
23  0.9995843 0.0004165503 1.001609 DEL   TRUE
24         NA 1.0008183503 1.000818 CNN  FALSE
25         NA           NA       NA CNN  FALSE
26         NA 1.0008183503 1.000818 CNN  FALSE
27         NA           NA       NA CNN  FALSE
28         NA 1.0008183503 1.000818 CNN  FALSE
29         NA 1.0008183503 1.000818 CNN  FALSE
30         NA           NA       NA CNN  FALSE
⋮   ⋮         ⋮            ⋮        ⋮    ⋮
295 NA        NA           NA       CNN  FALSE
296 NA        NA           NA       CNN  FALSE
297 NA        NA           NA       CNN  FALSE
298 NA        NA           NA       CNN  FALSE
299 NA        NA           NA       CNN  FALSE
300 NA        NA           NA       CNN  FALSE
301 NA        NA           NA       CNN  FALSE
302 NA        NA           NA       CNN  FALSE
303 NA        NA           NA       CNN  FALSE
304 NA        NA           NA       CNN  FALSE
305 NA        NA           NA       CNN  FALSE
306 NA        NA           NA       CNN  FALSE
307 NA        NA           NA       CNN  FALSE
308 NA        NA           NA       CNN  FALSE
309 NA        NA           NA       CNN  FALSE
310 NA        NA           NA       CNN  FALSE
311 NA        NA           NA       CNN  FALSE
312 NA        NA           NA       HDEL FALSE
313 NA        NA           NA       CNN  FALSE
314 NA        NA           NA       CNN  FALSE
315 NA        NA           NA       CNN  FALSE
316 NA        NA           NA       CNN  FALSE
317 NA        NA           NA       HDEL FALSE
318 NA        NA           NA       CNN  FALSE
319 NA        NA           NA       CNN  FALSE
320 NA        NA           NA       CNN  FALSE
321 NA         0            0       HDEL FALSE
322 NA         0            0       HDEL FALSE
323 NA        NA           NA       HDEL FALSE
324 NA        NA           NA       CNN  FALSE
    Gene
1   RP11-54O7.16,RP11-54O7.1,RP11-54O7.2,RP11-54O7.3,SAMD11,AL645608.1,NOC2L,KLHL17,PLEKHN1,C1orf170,RP11-54O7.17,HES4,RP11-54O7.10,RP11-54O7.11,ISG15,AGRN,RP11-54O7.14,RP11-465B22.3,RP11-54O7.18,RNF223,C1orf159,RP11-465B22.5,MIR200B,MIR200A,MIR429,RP11-465B22.8,TTLL10-AS1,TTLL10,TNFRSF18,TNFRSF4,SDF4,B3GALT6,FAM132A,RP5-902P8.12,UBE2J2,RP5-902P8.10,SCNN1D,ACAP3,PUSL1,CPSF3L,RP5-890O3.9,GLTPD1,TAS1R3,DVL1,MXRA8,AURKAIP1,RP5-890O3.3,CCNL2,RP4-758J18.2,MRPL20,RN7SL657P,RP4-758J18.13,ANKRD65,RP4-758J18.7,TMEM88B,RP4-758J18.10,VWA1,ATAD3C,ATAD3B,ATAD3A,TMEM240,SSU72,AL645728.2,AL645728.1,AL645728.3,C1orf233,RP11-345P4.9,MIB2,MMP23B,CDK11B,RP11-345P4.10,SLC35E2B,RP11-345P4.7,RP11-345P4.6,MMP23A,CDK11A,RP1-283E3.8,RP1-283E3.4,SLC35E2,NADK,GNB1,RP1-140A9.1,CALML6,TMEM52,C1orf222,RP11-547D24.1,GABRD,RP11-547D24.3,PRKCZ,RP5-892K4.1,RP11-181G12.2,C1orf86,AL590822.2,AL590822.1,RP11-181G12.5,RP11-181G12.4,SKI,MORN1,RP4-713A8.1,AL589739.1,RP4-740C4.6,RP4-740C4.5,RP4-740C4.7,RP4-740C4.9,RP4-740C4.8,AL513477.1,RER1,PEX10,PLCH2,RP3-395M20.2,RP3-395M20.3,PANK4,HES5,RP3-395M20.12,RP3-395M20.8,TNFRSF14,RP3-395M20.7,RP3-395M20.9,FAM213B,MMEL1,RP13-436F16.1,TTC34,RP11-740P5.2,RP11-740P5.3,ACTRT2,LINC00982,AL008733.1,PRDM16,RP1-163G9.2,RP11-22L13.1,ARHGEF16,RP11-168F9.2,MEGF6,MIR551A,RP11-46F15.2,TPRG1L,WRAP73,TP73,RP5-1092A11.5,RP5-1092A11.2,TP73-AS1,CCDC27,SMIM1,LRRC47,RN7SL574P,RP1-286D6.5,CEP104,DFFB,AL691523.1,C1orf174,RP13-15E13.1,RP13-614K11.1,RP13-614K11.2,RP11-374C13.1,RP5-1166F10.1,RP1-37J18.1,RP1-37J18.2,AJAP1,RP11-542C10.1,RP1-58B11.1,MIR4417,RP11-154H17.1,AL356693.1,MIR4689,NPHP4,AL356261.1,KCNAB2,AL035406.1,CHD5,RPL22,RP1-120G22.11,RNF207,ICMT,LINC00337,HES3,GPR153,ACOT7,RP1-202O8.3,HES2,ESPN,MIR4252,RP1-202O8.2,TNFRSF25,PLEKHG5,NOL9,RNU6-731P,RP11-58A11.2,TAS1R1,ZBTB48,KLHL21,PHF13,THAP3,DNAJC11,RP11-242F24.1,snoU13,RP11-312B8.1,CAMTA1,RP11-312B8.2,RP11-334N17.1,RNU1-8P,CAMTA1-IT1,RP3-453P22.2,RP4-549F15.1,RP11-338N10.1,RP11-338N10.2,RP11-338N10.3,VAMP3,RP3-467L1.6,PER3,RP3-467L1.4,UTS2,TNFRSF9,RP5-892F13.2,PARK7,Y_RNA,ERRFI1,RP11-431K24.1,CTA-215D11.4,RP11-431K24.2,RNU1-7P,RP11-431K24.3,RP11-431K24.4,RN7SL729P,RNU6-991P,SLC45A1,Y_RNA,RERE,RP5-1115A15.1,SNORA77,RP5-1115A15.2,RP4-633I8.1,RP4-633I8.2,Y_RNA,RP4-633I8.3,RP4-633I8.4,RP11-185B14.1,ENO1,ENO1-IT1,ENO1-AS1,RNU6-304P,HMGN2P17,RP3-477M7.5,RP3-477M7.6,CA6,RN7SL451P,SLC2A7,SLC2A5,SCARNA16,GPR157,MIR34A,RP3-510D11.1,RP3-510D11.2,H6PD,Z98044.1,SPSB1,RNA5SP40,RP13-392I16.1,SLC25A33,RP13-15M17.1,TMEM201,PIK3CD,C1orf200,RP11-558F24.2,RP11-558F24.4,CLSTN1,RP11-558F24.6,CTNNBIP1,RP11-84A14.5,LZIC,RP11-84A14.4,NMNAT1,RN7SKP269,MIR5697,RP11-807G9.2,RBP7,AL590639.1,UBE4B,RP11-496H15.2,PGAM1P11,RNU6-828P,KIF1B,MIR1273D,RNU6-37P,RN7SL731P,RN7SL721P,PGD,RP4-736L20.3,APITD1,APITD1-CORT,CORT,DFFA,RP5-1113E3.3,PEX14,RN7SL614P,CASZ1,RP4-734G22.3,RP11-340B24.3,C1orf127,CFL1P6,AL713997.1,Y_RNA,TARDBP,MASP2,RP4-635E18.8,SRM,EXOSC10,RP4-635E18.7,RP4-635E18.6,MTOR,MTOR-AS1,RNU6-537P,snoU13,ANGPTL7,RNU6-291P,RPL39P6,UBIAD1,UBE2V2P3,RP11-149P14.1,PTCHD2,RP1-69M21.2,FBXO2,FBXO44,FBXO6,MAD2L2,DRAXIN,AGTRAP,C1orf167,RP11-56N19.5,MTHFR,CLCN6,NPPA-AS1,NPPA,NPPB,RP5-934G17.6,RNU5E-1,RNU5E-4P,KIAA2013,PLOD1,MFN2,RP5-1077B9.5,MIIP,Y_RNA,RN7SL649P,TNFRSF8,RNU6-777P,RP11-426M1.2,TNFRSF1B,MIR4632,RP5-1118D24.2,SNORA70,VPS13D,SNORA59A,RP5-888M10.2,DHRS3,RNU6ATAC18P,RP11-474O21.5,AADACL4,RP11-474O21.2,AADACL3,snoU13,C1orf158,PRAMEF12
2   LRRC38,RP4-597A16.2,RP4-597A16.3,PDPN,RNA5SP41,AL359771.1,CTA-520D8.2,SCARNA11,PRDM2,RNU6-1265P,RP11-344F13.1,RP4-704D23.1,KAZN,TBCAP2,TMEM51-AS1,TMEM51,C1orf195,RP1-21O18.3,FHAD1,RP3-467K16.2,RP3-467K16.7,RP3-467K16.4,EFHD2,CTRC,CELA2A,CELA2B,CASP9,DNAJC16,SCARNA21,RP4-680D5.8,AGMAT,RP4-680D5.2,CHCHD2P6,RNU7-179P,RP4-680D5.4,DDI2,RSC1A1,RP4-680D5.9,PLEKHM2,AL121992.1,RP11-288I21.1,SLC25A34,RP11-169K16.4,TMEM82,FBLIM1,RP11-169K16.6,RP11-169K16.7,RP11-169K16.8,RP11-169K16.9,SPEN,snoU13,RP1-134O19.3,ZBTB17,RP11-5P18.1,RP11-5P18.3,TBC1D3P6,C1orf64,RP11-5P18.5,HSPB7,CLCNKA,RP11-5P18.10,CLCNKB,FAM131C,EPHA2,RP11-276H7.2,RP11-276H7.3,ARHGEF19-AS1,ARHGEF19,ANO7P1,C1orf134,RSG1,MT1XP1,FBXO42,SZRD1,RP11-430L17.1,SPATA21,NECAP2,RP4-798A10.2,CROCCP3,RNU1-1,RP4-798A10.7,RP4-798A10.4,U1,AL355149.2,RP5-875O13.6,AL355149.1,NBPF1,RP5-1182A14.5,CROCCP2,MST1P2,RNU1-3,AL137798.1,AL021920.1,EIF1AXP1,ESPNP,AL021920.2,CROCC,RNU1-4,CROCCP4,MST1L,RP11-108M9.1,RP11-108M9.2,MIR3675,U1,RP11-108M9.4,RP11-108M9.5,RNU1-2,RP11-108M9.6,MFAP2,RP1-37C10.3,ATP13A2,SDHB,PADI2,Y_RNA,RP11-380J14.1,PADI1,PADI3,MIR3972,PADI4,AC004824.2,PADI6,RP1-20B21.4,RCC2,AC004824.1,snoU13,ARHGEF10L,RP11-473A10.2,ACTL8,RP11-174G17.2,IGSF21,RP11-174G17,RP11-422P22.1,KLHDC7A,RP1-8B22.1,RP1-8B22.2,PAX7,TAS1R2,RP13-279N23.2,ALDH4A1,MIR4695,MIR1290,IFFO2,RP5-1126H10.2,UBR4,AL137127.1
3   UBR4
4   UBR4,RP1-43E13.2,EMC1,MRTO4,AKR7L,AKR7A3,RP4-657E11.10,AKR7A2,RNU6-1099P,PQLC2,RN7SL85P,CAPZB,RN7SL277P,RNU4-28P,snoU13,RP5-1056L3.1,MINOS1-NBL1,MINOS1,RPS14P3,NBL1,HTR6,TMCO4,RNF186,RP11-91K11.2,OTUD3,PLA2G2E,RN7SL304P,PLA2G2A,PLA2G5,PLA2G2D,PLA2G2F,RP3-340N1.2,PLA2G2C,RP3-340N1.5,UBXN10,RP3-340N1.6,VWA5B1,RP4-745E8.2,RP4-749H3.1,RP4-749H3.2,CAMK2N1,MUL1,RPS4XP4,FAM43B,CDA,PINK1,PINK1-AS,AL391357.1,DDOST,KIF17,RP5-930J4.5,SH2D5,RP5-930J4.2,HP1BP3,RP5-930J4.4,EIF4G3,RNU7-200P,MIR1256,RPS15AP6,RP11-487E1.2,RP11-628K18.1,AL031005.1,ECE1,RP3-329E20.2,RP5-1071N3.1,PPP1R11P1,RP11-293F5.8,RP11-293F5.1,NBPF2P,HS6ST1P1,CROCCP5,NBPF3,PFN1P10,ALPL,RP11-63N8.3,AL359815.1,RAP1GAP,USP48,RP11-132G19.3,LDLRAD2,HSPG2,RP11-26H16.1,CELA3B,RN7SL421P,RN7SL386P,RNU6-1022P,CELA3A,RN7SL768P,RN7SL186P,RNU6-776P,RP1-224A6.3,LINC00339,CDC42,CDC42-IT1,RP1-224A6.8,RP1-224A6.9,WNT4,MIR4418,RP11-415K20.1,ZBTB40,ZBTB40-IT1,EPHA8,C1QA,C1QC,C1QB,EPHB2,MIR4684,AL611946.1,RP11-69E9.1,MIR4253,RP1-74M1.3,LACTBL1,C1orf234,KDM1A,RP1-184J9.2,MIR3115,MIR4419A,LUZP1,RP5-979D14.1,RNU6-514P,RNU6-135P,HTR1D,RP5-1057J7.1,RP5-1057J7.6,HNRNPR,ZNF436,C1orf213,Y_RNA,RP5-1057J7.7,TCEA3,RP4-654C18.1,ASAP3,E2F2,RP1-150O5.3,ID3,MDS2,RP11-223J15.2,RPL11,RP5-886K2.1,RN7SL532P,TCEB3,RP5-886K2.3,PITHD1,LYPLA2,GALE,HMGCL,FUCA1,CNR2,RN7SL24P,snoU13,RP11-4M23.2,RP11-4M23.3,MIR378F,RP11-4M23.4,PNRC2,SRSF10,RP11-4M23.7,RP11-293P20.2,MYOM3,RP11-293P20.4,IL22RA1,IFNLR1,RP11-10N16.2,AL590683.1,AL590683.2,RP11-10N16.3,GRHL3,STPG1,NIPAL3,RCAN3,RN7SL857P,RP4-594I10.3,NCMAP,RP11-496D1.2,Y_RNA,SRRM1,snoU13,CLIC4,RNU6-1208P,RUNX3,RP11-84D1.1,RP11-84D1.2,MIR4425,RP4-799D16.1,RP4-781L3.1
5   NA

In [5]:
cnv <- fread("/omics/odcf/analysis/hipo/hipo_021/outlier_analysis/vcf/cnv/cnv.tsv")
dim(cnv)

[1] 1551825      15

In [6]:
rna_gt <- readRDS("/omics/odcf/analysis/hipo/hipo_021/outlier_analysis/drop_runs/drop_master_202502_allGenes/processed_data/mae/RNA_GT/DMENTM8.Rds")
rna_gt

GRanges object with 984 ranges and 1 metadata column:
        seqnames    ranges strand |      RNA_GT
           <Rle> <IRanges>  <Rle> | <character>
    [1]        1   1342612      * |         0/0
    [2]        1   1469546      * |         0/1
    [3]        1   2522204      * |         0/0
    [4]        1   3544187      * |         0/0
    [5]        1   6651093      * |         0/0
    ...      ...       ...    ... .         ...
  [980]        9 137734232      * |         0/1
  [981]        9 138396251      * |         0/1
  [982]        9 138831567      * |         0/0
  [983]        9 139566996      * |         0/0
  [984]        9 139732462      * |         0/0
  -------
  seqinfo: 22 sequences from an unspecified genome; no seqlengths

In [34]:
cnv_type <- as.data.table(assay(cnv, "Type"))
cnv_type[ WGS.MNL8UP.tumor == 1,]

  WGS.MNL8UP.tumor
1 1
2 1

In [10]:
assayNames(cnv_germline)

[1] "Type"       "CN"         "NP"         "QUAL"       "Confidence"
[6] "Gene"

In [ ]:
cdt <- as.data.table(colData(cnv))
colnames(cdt)
cdt[, c("SampleID", "VersionCNV", "")]

 [1] "SampleID"                   "ProjectID"
 [3] "PatientID"                  "TumorID"
 [5] "ControlID"                  "DNASeq"
 [7] "RNASample"                  "NoDataReason"
 [9] "DNASampleChar"              "Ploidy"
[11] "TumorCellContent"           "CNVSolutionConfidence"
[13] "CNVSolutionMTB"             "DegradationControl"
[15] "DegradationTumor"           "TelomereTiltControl"
[17] "TelomereTiltTumor"          "SufficientTumorCellContent"
[19] "SevereDegradation"          "Comment"
[21] "DNASeqDateTumor"            "DNASeqDateControl"
[23] "RNASeqDate"                 "DNAPlatformTumor"
[25] "DNAPlatformControl"         "RNAPlatform"
[27] "DNAPrepKitControl"          "DNAPrepKitTumor"
[29] "DNAPrepKitCNV"              "RNAPrepKit"
[31] "DNATumorID"                 "DNAControlID"
[33] "RNASampleID"                "TissueMaterial"
[35] "Sex"                        "VersionSNV"
[37] "VersionInDel"               "VersionGermlineSmallVar"
[39] "VersionGermlineCNV"         "VersionCNV"
[41] "VersionSV"                  "VersionMSI"
[43] "VersionRNA"                 "VersionFusion"
[45] "LOH.HRD"                    "LST"
[47] "TAI"                        "MSI"
[49] "AdaptorHopping"             "INDEL_SomaticRescue"
[51] "INDEL_SomaticPass"          "SNV_dbSNP"
[53] "SNV_TotalSomatic"           "INDEL_TotalSomatic"
[55] "SNV_TotalGermline"          "INDEL_TotalGermline"
[57] "SNV_ClinFunOnTarget"        "INDEL_ClinFunOnTarget"
[59] "MutPerMb"

In [11]:
rdt <- as.data.table(rowData(cnv))
rdt

        TCN       CovRatio  BAF       c1Mean    c2Mean    Type LOH
1       1.905110  0.9573419        NA 0.9525552 0.9525552 CNN  FALSE
2       2.197807  1.1044254 0.6166911 0.8424388 1.3553678 CNN  FALSE
3       1.974623  0.9922730        NA        NA        NA CNN  FALSE
4       2.197097  1.1040687 0.6068063 0.8638846 1.3332122 CNN  FALSE
5       1.993741  1.0018799        NA 0.9968705 0.9968705 CNN  FALSE
6       1.914905  0.9622638        NA 0.9574525 0.9574525 CNN  FALSE
7       2.225633  1.1184083        NA        NA        NA CNN  FALSE
8       1.980018  0.9949837        NA 0.9900088 0.9900088 CNN  FALSE
9       2.664904  1.3391476        NA        NA        NA NA   FALSE
10      2.038789  1.0245172        NA 1.0193946 1.0193946 CNN  FALSE
11      1.950958  0.9803809        NA 0.9754790 0.9754790 CNN  FALSE
12      2.102965  1.0567663 0.6097827 0.8206133 1.2823516 CNN  FALSE
13      2.039114  1.0246805 0.6428244 0.7283218 1.3107925 CNN  FALSE
14      2.245798  1.1285419 0.6465496 0.7937783 1.4520201 CNN  FALSE
15      1.816874  0.9130020        NA        NA        NA CNN  FALSE
16      2.123144  1.0669068 0.5920337 0.8661714 1.2569731 CNN  FALSE
17      1.829666  0.9194302        NA        NA        NA CNN  FALSE
18      2.160800  1.0858291 0.5907402 0.8843284 1.2764714 CNN  FALSE
19      1.963789  0.9868285        NA        NA        NA CNN  FALSE
20      2.124767  1.0677223 0.5967144 0.8568880 1.2678794 CNN  FALSE
21      1.885616  0.9475455 0.5997320 0.7547516 1.1308641 CNN  FALSE
22      1.997697  1.0038678        NA 0.9988484 0.9988484 CNN  FALSE
23      1.714773  0.8616949        NA        NA        NA CNN  FALSE
24      1.997208  1.0036220        NA 0.9986039 0.9986039 CNN  FALSE
25      1.928737  0.9692144        NA 0.9643683 0.9643683 CNN  FALSE
26      1.726000  0.8673367        NA        NA        NA CNN  FALSE
27      1.937874  0.9738058        NA 0.9689368 0.9689368 CNN  FALSE
28      2.169352  1.0901268        NA 1.0846762 1.0846762 CNN  FALSE
29      1.731282  0.8699908        NA        NA        NA CNN  FALSE
30      2.167550  1.0892212        NA 1.0837751 1.0837751 CNN  FALSE
⋮       ⋮         ⋮         ⋮         ⋮         ⋮         ⋮    ⋮
2236937 2.0007488 1.2397    NA        NA        NA        NA   FALSE
2236938 2.0363916 1.2605    NA        NA        NA        NA   FALSE
2236939 3.9890337 2.4000    NA        NA        NA        DUP  FALSE
2236940 4.4227447 2.6531    NA        NA        NA        AMP  FALSE
2236941 3.8755937 2.3338    NA        NA        NA        DUP  FALSE
2236942 2.9350011 1.7849    NA        NA        NA        DUP  FALSE
2236943 2.9631041 1.8013    NA        NA        NA        DUP  FALSE
2236944 3.9184336 2.3588    NA        NA        NA        DUP  FALSE
2236945 4.3274688 2.5975    NA        NA        NA        AMP  FALSE
2236946 3.8994127 2.3477    NA        NA        NA        DUP  FALSE
2236947 3.8983845 2.3471    NA        NA        NA        DUP  FALSE
2236948 3.8791922 2.3359    NA        NA        NA        DUP  FALSE
2236949 3.8368664 2.3112    NA        NA        NA        DUP  FALSE
2236950 3.8913588 2.3430    NA        NA        NA        DUP  FALSE
2236951 3.9182622 2.3587    NA        NA        NA        DUP  FALSE
2236952 3.9604167 2.3833    NA        NA        NA        DUP  FALSE
2236953 4.3509451 2.6112    NA        NA        NA        AMP  FALSE
2236954 3.8368664 2.3112    NA        NA        NA        DUP  FALSE
2236955 3.7965969 2.2877    NA        NA        NA        DUP  FALSE
2236956 3.7953974 2.2870    NA        NA        NA        DUP  FALSE
2236957 1.0486752 0.6841    NA        NA        NA        NA   FALSE
2236958 0.0000000 0.0000    NA         0         0        HDEL FALSE
2236959 0.0000000 0.0000    NA         0         0        HDEL FALSE
2236960 0.9542561 0.6290    NA        NA        NA        NA   FALSE
2236961 0.9283808 0.6139    NA        NA        NA        NA   FALSE
2236962 1.1211603 0.7264    NA        NA        NA        NA   FALSE
2236963 2.7513037 1.6777    NA        NA        NA        DUP  FALSE
2236964 2.8837646 1.7550    NA        NA        NA        DUP  FALSE
2236965 2.8530912 1.7371    NA        NA        NA        DUP  FALSE
2236966 1.7397683 1.0874    NA        NA        NA        CNN  FALSE